import { ElementRegistryEntry, ElementType } from "../types/elements";

const contentChildren: ElementType[] = [
  "heading", "paragraph", "rich-text", "list", "quote", "badge", "button", "link", "button-group",
  "image", "video-embed", "map-embed", "gallery", "service-card", "testimonial-card", "pricing-card",
  "business-hours", "location-card", "contact-card", "announcement-bar", "emergency-banner", "coupon-card",
  "form", "custom-html", "custom-code-placeholder"
];

const layoutChildren: ElementType[] = ["container", "grid", "stack", "cluster", "split", "card", "group", ...contentChildren];
const formChildren: ElementType[] = ["input", "textarea", "select", "checkbox", "radio", "submit-button"];
const normalParents: ElementType[] = ["section", "container", "grid", "stack", "cluster", "split", "card", "group"];

function entry(input: ElementRegistryEntry): ElementRegistryEntry {
  return input;
}

export const elementRegistry: Record<ElementType, ElementRegistryEntry> = {
  "page-root": entry({ type: "page-root", label: "Page root", category: "structural", canHaveChildren: true, allowedChildren: ["section", "announcement-bar", "emergency-banner"], allowedParents: [], defaultContent: {}, defaultDesign: {}, defaultClasses: ["ss-site-page"], editableFields: ["label"], requiredFields: [], renderCategory: "page", safeForPublish: true, builderOnly: false }),
  section: entry({ type: "section", label: "Section", category: "structural", canHaveChildren: true, allowedChildren: layoutChildren, allowedParents: ["page-root"], defaultContent: { sectionType: "custom" }, defaultDesign: { spacing: "comfortable", background: "default", width: "wide" }, defaultClasses: ["ss-section"], editableFields: ["label", "content.sectionType", "design", "classes", "attributes", "visibility"], requiredFields: [], renderCategory: "section", safeForPublish: true, builderOnly: false }),
  container: entry({ type: "container", label: "Container", category: "structural", canHaveChildren: true, allowedChildren: layoutChildren, allowedParents: ["section", "container", "grid", "stack", "cluster", "split", "card", "group"], defaultContent: {}, defaultDesign: { width: "wide" }, defaultClasses: ["ss-section-wide"], editableFields: ["label", "design", "classes", "attributes", "visibility"], requiredFields: [], renderCategory: "layout", safeForPublish: true, builderOnly: false }),
  grid: entry({ type: "grid", label: "Grid", category: "structural", canHaveChildren: true, allowedChildren: ["card", "group", ...contentChildren], allowedParents: ["section", "container", "group"], defaultContent: { layout: "halves-vertical" }, defaultDesign: { spacing: "comfortable", variant: "halves-vertical" }, defaultClasses: ["ss-grid", "ss-cols-2", "ss-gap-6"], editableFields: ["label", "content.layout", "design", "classes"], requiredFields: [], renderCategory: "layout", safeForPublish: true, builderOnly: false }),
  stack: entry({ type: "stack", label: "Stack", category: "structural", canHaveChildren: true, allowedChildren: layoutChildren, allowedParents: ["section", "container", "card", "group"], defaultContent: {}, defaultDesign: { spacing: "comfortable" }, defaultClasses: ["ss-stack"], editableFields: ["label", "design", "classes"], requiredFields: [], renderCategory: "layout", safeForPublish: true, builderOnly: false }),
  cluster: entry({ type: "cluster", label: "Cluster", category: "structural", canHaveChildren: true, allowedChildren: contentChildren, allowedParents: ["section", "container", "group"], defaultContent: {}, defaultDesign: {}, defaultClasses: ["ss-row", "ss-wrap"], editableFields: ["label", "design", "classes"], requiredFields: [], renderCategory: "layout", safeForPublish: true, builderOnly: false }),
  split: entry({ type: "split", label: "Split", category: "structural", canHaveChildren: true, allowedChildren: layoutChildren, allowedParents: ["section", "container", "group"], defaultContent: {}, defaultDesign: {}, defaultClasses: ["ss-section-split"], editableFields: ["label", "design", "classes"], requiredFields: [], renderCategory: "layout", safeForPublish: true, builderOnly: false }),
  card: entry({ type: "card", label: "Card", category: "structural", canHaveChildren: true, allowedChildren: contentChildren, allowedParents: ["section", "container", "grid", "stack", "group"], defaultContent: { title: "Card title", text: "Card text" }, defaultDesign: { radius: "soft", shadow: "soft" }, defaultClasses: ["ss-card"], editableFields: ["label", "content", "design", "classes"], requiredFields: [], renderCategory: "layout", safeForPublish: true, builderOnly: false }),
  group: entry({ type: "group", label: "Group", category: "structural", canHaveChildren: true, allowedChildren: layoutChildren, allowedParents: ["section", "container", "grid", "stack", "card"], defaultContent: {}, defaultDesign: {}, defaultClasses: [], editableFields: ["label", "design", "classes"], requiredFields: [], renderCategory: "layout", safeForPublish: true, builderOnly: false }),
  heading: entry({ type: "heading", label: "Heading", category: "content", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { text: "New heading", level: 2 }, defaultDesign: {}, defaultClasses: ["ss-h2"], editableFields: ["label", "content.text", "content.level", "design", "classes", "attributes"], requiredFields: ["text"], renderCategory: "text", safeForPublish: true, builderOnly: false }),
  paragraph: entry({ type: "paragraph", label: "Paragraph", category: "content", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { text: "New paragraph text." }, defaultDesign: {}, defaultClasses: ["ss-text"], editableFields: ["label", "content.text", "design", "classes"], requiredFields: ["text"], renderCategory: "text", safeForPublish: true, builderOnly: false }),
  "rich-text": entry({ type: "rich-text", label: "Rich text", category: "content", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { text: "Rich text content." }, defaultDesign: {}, defaultClasses: ["ss-content"], editableFields: ["label", "content.text", "classes"], requiredFields: ["text"], renderCategory: "text", safeForPublish: true, builderOnly: false }),
  list: entry({ type: "list", label: "List", category: "content", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { items: ["First item", "Second item"] }, defaultDesign: {}, defaultClasses: ["ss-list"], editableFields: ["label", "content.items", "classes"], requiredFields: ["items"], renderCategory: "text", safeForPublish: true, builderOnly: false }),
  quote: entry({ type: "quote", label: "Quote", category: "content", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { text: "Customer quote." }, defaultDesign: {}, defaultClasses: ["ss-blockquote"], editableFields: ["label", "content.text"], requiredFields: ["text"], renderCategory: "text", safeForPublish: true, builderOnly: false }),
  badge: entry({ type: "badge", label: "Badge", category: "content", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { text: "Badge" }, defaultDesign: { variant: "primary" }, defaultClasses: ["ss-badge"], editableFields: ["label", "content.text", "design.variant", "classes"], requiredFields: ["text"], renderCategory: "text", safeForPublish: true, builderOnly: false }),
  button: entry({ type: "button", label: "Button", category: "action", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { text: "Button", href: "#", target: "_self", variant: "primary" }, defaultDesign: { variant: "primary" }, defaultClasses: ["ss-btn"], editableFields: ["label", "content.text", "content.href", "content.target", "design.variant", "classes", "attributes"], requiredFields: ["text", "href"], renderCategory: "action", safeForPublish: true, builderOnly: false }),
  link: entry({ type: "link", label: "Link", category: "action", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents.concat(["nav"]), defaultContent: { text: "Link", href: "#", target: "_self" }, defaultDesign: {}, defaultClasses: ["ss-link"], editableFields: ["label", "content.text", "content.href", "content.target"], requiredFields: ["text", "href"], renderCategory: "action", safeForPublish: true, builderOnly: false }),
  "button-group": entry({ type: "button-group", label: "Button group", category: "action", canHaveChildren: true, allowedChildren: ["button", "link"], allowedParents: normalParents, defaultContent: {}, defaultDesign: {}, defaultClasses: ["ss-section-actions"], editableFields: ["label", "design", "classes"], requiredFields: [], renderCategory: "action", safeForPublish: true, builderOnly: false }),
  nav: entry({ type: "nav", label: "Navigation", category: "action", canHaveChildren: true, allowedChildren: ["nav-link"], allowedParents: ["page-root", "section", "container"], defaultContent: {}, defaultDesign: {}, defaultClasses: ["ss-nav"], editableFields: ["label", "classes"], requiredFields: [], renderCategory: "action", safeForPublish: true, builderOnly: false }),
  "nav-link": entry({ type: "nav-link", label: "Navigation link", category: "action", canHaveChildren: false, allowedChildren: [], allowedParents: ["nav"], defaultContent: { text: "Nav link", href: "#" }, defaultDesign: {}, defaultClasses: ["ss-navbar-link"], editableFields: ["label", "content.text", "content.href"], requiredFields: ["text", "href"], renderCategory: "action", safeForPublish: true, builderOnly: false }),
  image: entry({ type: "image", label: "Image", category: "media", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { src: "", alt: "Image", objectFit: "cover" }, defaultDesign: {}, defaultClasses: ["ss-media-frame"], editableFields: ["label", "content.src", "content.alt", "content.objectFit", "classes"], requiredFields: ["alt"], renderCategory: "media", safeForPublish: true, builderOnly: false }),
  "video-embed": entry({ type: "video-embed", label: "Video embed", category: "media", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { embedUrl: "" }, defaultDesign: {}, defaultClasses: ["ss-embed-video"], editableFields: ["label", "content.embedUrl"], requiredFields: ["embedUrl"], renderCategory: "media", safeForPublish: true, builderOnly: false }),
  "map-embed": entry({ type: "map-embed", label: "Map embed", category: "media", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { address: "", embedUrl: "" }, defaultDesign: {}, defaultClasses: ["ss-map-wrapper"], editableFields: ["label", "content.address", "content.embedUrl"], requiredFields: [], renderCategory: "media", safeForPublish: true, builderOnly: false }),
  gallery: entry({ type: "gallery", label: "Gallery", category: "media", canHaveChildren: true, allowedChildren: ["image"], allowedParents: normalParents, defaultContent: {}, defaultDesign: {}, defaultClasses: ["ss-gallery-grid"], editableFields: ["label", "design", "classes"], requiredFields: [], renderCategory: "media", safeForPublish: true, builderOnly: false }),
  "service-card": entry({ type: "service-card", label: "Service card", category: "business", canHaveChildren: false, allowedChildren: [], allowedParents: ["grid", "container", "section", "stack"], defaultContent: { title: "Service title", text: "Service description." }, defaultDesign: {}, defaultClasses: ["ss-service-card"], editableFields: ["label", "content", "design"], requiredFields: ["title"], renderCategory: "business", safeForPublish: true, builderOnly: false }),
  "testimonial-card": entry({ type: "testimonial-card", label: "Testimonial", category: "business", canHaveChildren: false, allowedChildren: [], allowedParents: ["grid", "container", "section", "stack"], defaultContent: { quote: "Customer quote.", name: "Customer name" }, defaultDesign: {}, defaultClasses: ["ss-testimonial-card"], editableFields: ["label", "content"], requiredFields: ["quote"], renderCategory: "business", safeForPublish: true, builderOnly: false }),
  "pricing-card": entry({ type: "pricing-card", label: "Pricing card", category: "business", canHaveChildren: false, allowedChildren: [], allowedParents: ["grid", "container", "section"], defaultContent: { title: "Package", price: "$99", features: [] }, defaultDesign: {}, defaultClasses: ["ss-pricing-card"], editableFields: ["label", "content"], requiredFields: ["title"], renderCategory: "business", safeForPublish: true, builderOnly: false }),
  "business-hours": entry({ type: "business-hours", label: "Business hours", category: "business", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { rows: [] }, defaultDesign: {}, defaultClasses: ["ss-business-hours-card"], editableFields: ["label", "content.rows"], requiredFields: [], renderCategory: "business", safeForPublish: true, builderOnly: false }),
  "location-card": entry({ type: "location-card", label: "Location card", category: "business", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { address: "" }, defaultDesign: {}, defaultClasses: ["ss-location-card"], editableFields: ["label", "content.address"], requiredFields: [], renderCategory: "business", safeForPublish: true, builderOnly: false }),
  "contact-card": entry({ type: "contact-card", label: "Contact card", category: "business", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { phone: "", email: "" }, defaultDesign: {}, defaultClasses: ["ss-contact-details-card"], editableFields: ["label", "content"], requiredFields: [], renderCategory: "business", safeForPublish: true, builderOnly: false }),
  "announcement-bar": entry({ type: "announcement-bar", label: "Announcement bar", category: "business", canHaveChildren: false, allowedChildren: [], allowedParents: ["page-root", "section"], defaultContent: { text: "Announcement" }, defaultDesign: {}, defaultClasses: ["ss-announcement-bar"], editableFields: ["label", "content.text"], requiredFields: ["text"], renderCategory: "business", safeForPublish: true, builderOnly: false }),
  "emergency-banner": entry({ type: "emergency-banner", label: "Emergency banner", category: "business", canHaveChildren: false, allowedChildren: [], allowedParents: ["page-root", "section"], defaultContent: { text: "Emergency service available" }, defaultDesign: {}, defaultClasses: ["ss-emergency-banner"], editableFields: ["label", "content.text"], requiredFields: ["text"], renderCategory: "business", safeForPublish: true, builderOnly: false }),
  "coupon-card": entry({ type: "coupon-card", label: "Coupon card", category: "business", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { title: "Offer", code: "SAVE" }, defaultDesign: {}, defaultClasses: ["ss-coupon-card"], editableFields: ["label", "content"], requiredFields: ["title"], renderCategory: "business", safeForPublish: true, builderOnly: false }),
  form: entry({ type: "form", label: "Form", category: "form", canHaveChildren: true, allowedChildren: formChildren, allowedParents: normalParents, defaultContent: {}, defaultDesign: {}, defaultClasses: ["ss-form-safe"], editableFields: ["label", "classes"], requiredFields: [], renderCategory: "form", safeForPublish: true, builderOnly: false }),
  input: entry({ type: "input", label: "Input", category: "form", canHaveChildren: false, allowedChildren: [], allowedParents: ["form"], defaultContent: { name: "field", label: "Field", placeholder: "", required: false, validationType: "text" }, defaultDesign: {}, defaultClasses: [], editableFields: ["label", "content"], requiredFields: ["name", "label"], renderCategory: "form", safeForPublish: true, builderOnly: false }),
  textarea: entry({ type: "textarea", label: "Textarea", category: "form", canHaveChildren: false, allowedChildren: [], allowedParents: ["form"], defaultContent: { name: "message", label: "Message", required: false }, defaultDesign: {}, defaultClasses: [], editableFields: ["label", "content"], requiredFields: ["name", "label"], renderCategory: "form", safeForPublish: true, builderOnly: false }),
  select: entry({ type: "select", label: "Select", category: "form", canHaveChildren: false, allowedChildren: [], allowedParents: ["form"], defaultContent: { name: "select", label: "Select", options: [] }, defaultDesign: {}, defaultClasses: [], editableFields: ["label", "content"], requiredFields: ["name", "label"], renderCategory: "form", safeForPublish: true, builderOnly: false }),
  checkbox: entry({ type: "checkbox", label: "Checkbox", category: "form", canHaveChildren: false, allowedChildren: [], allowedParents: ["form"], defaultContent: { name: "checkbox", label: "Checkbox" }, defaultDesign: {}, defaultClasses: [], editableFields: ["label", "content"], requiredFields: ["name", "label"], renderCategory: "form", safeForPublish: true, builderOnly: false }),
  radio: entry({ type: "radio", label: "Radio", category: "form", canHaveChildren: false, allowedChildren: [], allowedParents: ["form"], defaultContent: { name: "radio", label: "Radio" }, defaultDesign: {}, defaultClasses: [], editableFields: ["label", "content"], requiredFields: ["name", "label"], renderCategory: "form", safeForPublish: true, builderOnly: false }),
  "submit-button": entry({ type: "submit-button", label: "Submit button", category: "form", canHaveChildren: false, allowedChildren: [], allowedParents: ["form"], defaultContent: { text: "Submit" }, defaultDesign: { variant: "primary" }, defaultClasses: ["ss-btn"], editableFields: ["label", "content.text", "design.variant"], requiredFields: ["text"], renderCategory: "form", safeForPublish: true, builderOnly: false }),
  "custom-html": entry({ type: "custom-html", label: "Custom HTML", category: "advanced", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { html: "" }, defaultDesign: {}, defaultClasses: [], editableFields: ["label", "content.html"], requiredFields: [], renderCategory: "advanced", safeForPublish: false, builderOnly: false }),
  "custom-code-placeholder": entry({ type: "custom-code-placeholder", label: "Custom code placeholder", category: "advanced", canHaveChildren: false, allowedChildren: [], allowedParents: normalParents, defaultContent: { note: "Custom code is managed outside the visual tree." }, defaultDesign: {}, defaultClasses: ["ss-builder-placeholder"], editableFields: ["label"], requiredFields: [], renderCategory: "advanced", safeForPublish: false, builderOnly: true })
};

export function registryEntry(type: ElementType): ElementRegistryEntry {
  return elementRegistry[type];
}

export function elementTypeExists(type: string): type is ElementType {
  return Object.prototype.hasOwnProperty.call(elementRegistry, type);
}

export function canContain(parentType: ElementType, childType: ElementType): boolean {
  const parent = registryEntry(parentType);
  const child = registryEntry(childType);
  if (!parent.canHaveChildren) return false;
  const childAllowed = parent.allowedChildren === "*" || parent.allowedChildren.includes(childType);
  const parentAllowed = child.allowedParents === "*" || child.allowedParents.includes(parentType);
  return childAllowed && parentAllowed;
}

export function registryByCategory(): Record<string, ElementRegistryEntry[]> {
  return Object.values(elementRegistry).reduce<Record<string, ElementRegistryEntry[]>>((groups, item) => {
    groups[item.category] ??= [];
    groups[item.category].push(item);
    return groups;
  }, {});
}

